# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale: "en_US" # Update to your preferred locale
title: "Rohit Chettri - Data Analytics Portfolio"
description: "BSc in Computer Science | Data Analytics Enthusiast"
url: "https://rohitchettri1303.github.io" # Update to your GitHub Pages URL
baseurl: "" # Keep it empty unless your site is hosted in a subdirectory

# Teaser Image
teaser: "assets/images/teaser-image.jpg" # Update to the path of your teaser image

# Breadcrumbs
breadcrumbs: true # Enable breadcrumbs for improved navigation

# Reading Time
words_per_minute: 200 # Adjust based on your content

# Future posts
future: false # Change to false if you don't want to publish future-dated posts

# Social Sharing
twitter:
  username: "your_twitter_handle"
facebook:
  username: "your_facebook_username"
  app_id: "your_facebook_app_id"
  publisher: "your_facebook_publisher"
og_image: "assets/images/og-image.jpg" # Update to the path of your Open Graph image

# Analytics
analytics:
  provider: "google-universal" # Change to "false" if you don't want analytics
  google:
    tracking_id: "your_google_analytics_tracking_id"

# Site Author
author:
  name: "Rohit Chettri"
  avatar: "assets/images/Rohit_img.png" # Update to the path of your avatar
  bio: "BSc in Computer Science | Data Analytics Enthusiast"
  location: "Bangalore, India"
  email: "rohitchettri1303@gmail.com"
  github: "rohitchettri1303"
  linkedin: "rohit-chettri-52a539247/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
